### ISSUE TITLE
Exception during sending mail

### ISSUE THREAD

**Issue by dgs28iun** [i4004/Simplify#53]
[21.12.2014 03:49:26:345] System.Net.Mail.SmtpException : Failure sending mail.
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at OnlineBookingWCF.Helpers.EmailHelper.EmailParams(List`1 eretailParams, String bookingType)
   at OnlineBookingWCF.ServiceOnlineBooking.GetGeneralBookingForm(GeneralBookingRequest request)
[Inner Exception] System.IO.IOException : Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Mail.SmtpPooledStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.Stream.Dispose()
   at System.Net.ConnectionPool.Destroy(PooledStream pooledStream)
   at System.Net.ConnectionPool.PutConnection(PooledStream pooledStream, Object owningObject, Int32 creationTimeout, Boolean canReuse)
   at System.Net.Mail.SmtpConnection.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpTransport.GetConnection(ServicePoint servicePoint)
   at System.Net.Mail.SmtpClient.GetConnection()
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
[Inner Exception 2] System.Net.Sockets.SocketException : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)

**Comment by i4004** [comment]
This is a correct behaviour, user is responsible to catch and process any System.Net exceptions has been thrown.
